; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = debug

[env]
platform = espressif32
board = esp32s3box
framework = arduino, espidf
monitor_filters = direct, esp32_exception_decoder
build_flags = -lstdc++ -std=gnu++2a
lib_deps = 
    zinggjm/GxEPD2@^1.6.2
    lvgl/lvgl@^9.2.2
monitor_speed = 115200
board_build.partitions = default_8MB.csv
;board_flash_size = 8MB
;board_upload.flash_size = 8MB

[env:debug]
build_type = debug
build_flags =
    -D LV_LVGL_H_INCLUDE_SIMPLE ; TODO(arosca): This is from LVGL 8. Some generated assets stil use this macro.
    -D LV_CONF_INCLUDE_SIMPLE
    -O0
    -g3
    -D CONFIG_BT_ENABLED=1
    -D CONFIG_BT_BLUEDROID_ENABLED=1
    -D CONFIG_BT_BLE_ENABLED=1
    -D CONFIG_BT_CLASSIC_ENABLED=0
    -D CONFIG_BTDM_CTRL_MODE_BLE_ONLY=1
    -D CONFIG_BT_BTC_TASK_STACK_SIZE=8192

[env:release]
build_type = release
build_flags =
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -Os
